In [8]:
%load_ext nb_black

<IPython.core.display.Javascript object>

# A jupyter notebook is a browser-based environment that integrates:
- A Kernel (python)
- Text
- Executable code
- Plots and images
- Rendered mathematical equations

## Cell

The basic unit of a jupyter notebook is a `cell`. A `cell` can contain any of the above elements. 

In a notebook, to run a cell of code, hit `Shift-Enter`. This executes the cell and puts the cursor in the next cell below, or makes a new one if you are at the end.  Alternately, you can use:
    
- `Alt-Enter` to force the creation of a new cell unconditionally (useful when inserting new content in the middle of an existing notebook).
- `Control-Enter` executes the cell and keeps the cursor in the same cell, useful for quick experimentation of snippets that you don't need to keep permanently.

## Hello World

In [24]:
print("Hello, Science!")

Hello, Science!


<IPython.core.display.Javascript object>

In [25]:
# lines that begin with a # are treated as comment lines and not executed

# print("This line is not printed")

print("This line is printed")

This line is printed


<IPython.core.display.Javascript object>

## Create a variable

In [26]:
my_variable = 3.0 * 2.0

<IPython.core.display.Javascript object>

## Print out the value of the variable

In [27]:
print(my_variable)

6.0


<IPython.core.display.Javascript object>

## or even easier:

In [28]:
my_variable

6.0

<IPython.core.display.Javascript object>

# Datatypes

In computer programming, a data type is a classification identifying one of various types that data
can have. 

The most common data type we will see in this class are:

* **Integers** (`int`): Integers are the classic cardinal numbers: ... -3, -2, -1, 0, 1, 2, 3, 4, ...

* **Floating Point** (`float`): Floating Point are numbers with a decimal point: 1.2, 34.98, -67,23354435, ...

* **Scientific Notation** - Floating point values can also be expressed in scientific notation: `1e3 = 1000`

* **Booleans** (`bool`): Booleans types can only have one of two values: `True` or `False`. In many languages 0 is considered `False`, and any other value is considered `True`.

* **Strings** (`str`): Strings can be composed of one or more characters: ’a’, ’spam’, ’spam spam eggs and spam’. Usually quotes (’) are used to specify a string. For example ’12’ would refer to the string, not the integer.

In [29]:
my_var_a = 1
my_var_b = 2.3
my_var_c = True
my_var_d = 'Spam'
my_var_e = '4.5'

<IPython.core.display.Javascript object>

In [30]:
type(my_var_a), type(my_var_b), type(my_var_c), type(my_var_d), type(my_var_e)

(int, float, bool, str, str)

<IPython.core.display.Javascript object>

In [31]:
my_var_a + my_var_b, type(my_var_a + my_var_b)

(3.3, float)

<IPython.core.display.Javascript object>

In [32]:
my_var_a + my_var_c, type(my_var_a + my_var_c)    # True = 1

(2, int)

<IPython.core.display.Javascript object>

In [33]:
my_var_b + my_var_e

TypeError: unsupported operand type(s) for +: 'float' and 'str'

<IPython.core.display.Javascript object>

In [34]:
str(my_var_b) + my_var_e

'2.34.5'

<IPython.core.display.Javascript object>

In [35]:
my_var_b + float(my_var_e)

6.8

<IPython.core.display.Javascript object>

# NumPy (Numerical Python) is the fundamental package for scientific computing with Python.

### Load the numpy library:

In [36]:
import numpy as np

<IPython.core.display.Javascript object>

#### pi and e are  built-in constants:

In [38]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

<IPython.core.display.Javascript object>

## Here is a link to all [Numpy math functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

----

# Arrays - Collections of datatypes

### Our basic array will be the NumPy array

* Each element of the array has a **Value**
* The *position* of each **Value** is called its **Index**

![Image of Index](./images/PosIndex_sm.png)

In [39]:
my_array = np.array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

In [40]:
my_array

array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

## Indexing

In [41]:
my_array[0]    # The Value at Index = 0

7

<IPython.core.display.Javascript object>

In [42]:
my_array[-1]    # The last Value in the array

3

<IPython.core.display.Javascript object>

![Image of Index](./images/NegIndex_sm.png)

## Slices

`x[start:stop:step]`
 
- `start` is the first Index that you want [default = first element]
- `stop`  is the first Index that you **do not** want [default = last element]
- `step`  defines size of `step` and whether you are moving forwards (positive) or backwards (negative) [default = 1]

In [43]:
my_array

array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

In [44]:
my_array[0:4]           # first 4 items

array([7, 4, 8, 5])

<IPython.core.display.Javascript object>

In [45]:
my_array[:4]            # same

array([7, 4, 8, 5])

<IPython.core.display.Javascript object>

In [46]:
my_array[0:4:2]         # first four item, step = 2

array([7, 8])

<IPython.core.display.Javascript object>

In [47]:
my_array[3::-1]         # first four items backwards, step = -1

array([5, 8, 4, 7])

<IPython.core.display.Javascript object>

In [48]:
my_array[::-1]          # Reverse the array x

array([3, 7, 5, 8, 4, 7])

<IPython.core.display.Javascript object>

In [49]:
print(my_array[-3:])    # last 3 elements of the array x

[5 7 3]


<IPython.core.display.Javascript object>

## There are lots of different `methods` that can be applied to a NumPy array

In [50]:
my_array.size                   # Number of elements in x

6

<IPython.core.display.Javascript object>

In [51]:
my_array.mean()                 # Average of the elements in x

5.666666666666667

<IPython.core.display.Javascript object>

In [52]:
my_array.sum()                  # Total of the elements in x

34

<IPython.core.display.Javascript object>

In [53]:
my_array[-3:].sum()              # Total of last 3 elements in x

15

<IPython.core.display.Javascript object>

In [54]:
my_array.cumsum()                # Cumulative sum

array([ 7, 11, 19, 24, 31, 34])

<IPython.core.display.Javascript object>

In [55]:
my_array.cumsum()/my_array.sum()        # Cumulative percentage

array([0.20588235, 0.32352941, 0.55882353, 0.70588235, 0.91176471,
       1.        ])

<IPython.core.display.Javascript object>

In [57]:
my_array

array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

## Help about a `method`:

In [59]:
?my_array.min

<IPython.core.display.Javascript object>

Docstring:
a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

Return the minimum along a given axis.

Refer to `numpy.amin` for full documentation.

See Also
--------
numpy.amin : equivalent function
Type:      builtin_function_or_method


## NumPy math works over an entire array:

In [60]:
my_array * 2

array([14,  8, 16, 10, 14,  6])

<IPython.core.display.Javascript object>

In [61]:
sin(my_array)     # need to Numpy's math functions

NameError: name 'sin' is not defined

<IPython.core.display.Javascript object>

In [62]:
np.sin(my_array)

array([ 0.6569866 , -0.7568025 ,  0.98935825, -0.95892427,  0.6569866 ,
        0.14112001])

<IPython.core.display.Javascript object>

## Masking - Filtering data

In [63]:
mask1 = np.where(my_array > 5)
my_array, mask1

(array([7, 4, 8, 5, 7, 3]), (array([0, 2, 4]),))

<IPython.core.display.Javascript object>

In [64]:
my_array[mask1]

array([7, 8, 7])

<IPython.core.display.Javascript object>

In [65]:
mask2 = np.where((my_array>3) & (my_array<6))
my_array[mask2]

array([4, 5])

<IPython.core.display.Javascript object>

In [66]:
mask3 = np.where(my_array >= 5)
my_array[mask3]

array([7, 8, 5, 7])

<IPython.core.display.Javascript object>

In [67]:
# Set all values of x that match mask3 to 0

my_array[mask3] = 0
my_array

array([0, 4, 0, 0, 0, 3])

<IPython.core.display.Javascript object>

## Sorting

In [68]:
my_array = np.array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

In [69]:
np.sort(my_array)

array([3, 4, 5, 7, 7, 8])

<IPython.core.display.Javascript object>

In [70]:
np.sort(my_array)[::-1]

array([8, 7, 7, 5, 4, 3])

<IPython.core.display.Javascript object>

In [71]:
np.sort(my_array)[0:3]

array([3, 4, 5])

<IPython.core.display.Javascript object>

# Control Flow

Like all computer languages, Python supports the standard types of control flows including:

* IF statements
* FOR loops

In [72]:
my_variable = -1

if my_variable > 0:

    print("This number is positive")

else:

    print("This number is NOT positive")

This number is NOT positive


<IPython.core.display.Javascript object>

In [73]:
my_variable = 0

if my_variable > 0:

    print("This number is positive")

elif my_variable == 0:

    print("This number is zero")

else:

    print("This number is negative")

This number is zero


<IPython.core.display.Javascript object>

## `For` loops are different in python.

You do not need to specify the beginning and end values of the loop

In [74]:
my_array

array([7, 4, 8, 5, 7, 3])

<IPython.core.display.Javascript object>

In [75]:
for value in my_array:
    print(value)

7
4
8
5
7
3


<IPython.core.display.Javascript object>

In [76]:
for index,value in enumerate(my_array):
    print(index,value)

0 7
1 4
2 8
3 5
4 7
5 3


<IPython.core.display.Javascript object>

In [77]:
for george,ringo in enumerate(my_array):
    print(george,ringo)

0 7
1 4
2 8
3 5
4 7
5 3


<IPython.core.display.Javascript object>

# Functions

In computer science, a `function` (also called a `procedure`, `method`, `subroutine`, or `routine`) is a portion
of code within a larger program that performs a specific task and is relatively independent of the
remaining code. The big advantage of a `function` is that it breaks a program into smaller, easier
to understand pieces. It also makes debugging easier. A `function` can also be reused in another
program.

The basic idea of a `function` is that it will take various values, do something with them, and `return` a result. The variables in a `function` are local. That means that they do not affect anything outside the `function`.

Below is an example of a `function` that solves the equation:

$ f(a,b,x) = b^{2}\cos(a^{2}\pi x)$

In the example the name of the `function` is **find_f** (you can name `functions` what ever you want). The `function` **find_f** takes three arguments `a`, `b` and `y`, and returns the value of the equation to the main program. In the main program a variable named `value_f` is assigned the value returned by **find_f**. Notice that in the main program the `function` **find_f** is called using the arguments `scalar_a`, `scalar_b` and `array_x`. Since the variables in the `function` are local, you do not have name them `a`, `b` and `x` in the main program.

In [78]:
def find_f(my_a, my_b, my_x):

    result = my_b ** 2 * np.cos(my_a ** 2 * np.pi * my_x)   # assign the variable result the value of the function
    return result                                           # return the value of the function to the main program

<IPython.core.display.Javascript object>

`np.linspace` -  create a new array filled with evenly spaced numbers over a specified interval `(start, stop, num)`

In [79]:
scalar_a = 7
scalar_b = 0.5
array_x = np.linspace(0, 2*np.pi, 20)

<IPython.core.display.Javascript object>

In [80]:
scalar_a, scalar_b, array_x

(7, 0.5, array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
        1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
        3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
        4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531]))

<IPython.core.display.Javascript object>

In [81]:
value_f = find_f(scalar_a, scalar_b, array_x)

value_f

array([ 0.25      ,  0.20038977,  0.07124847, -0.08617005, -0.20938924,
       -0.24950564, -0.19059778, -0.05604512,  0.10075084,  0.21756061,
        0.24802453,  0.18005201,  0.04062011, -0.11493317, -0.22487156,
       -0.24556251, -0.16879415, -0.02503446,  0.12866096,  0.23129317])

<IPython.core.display.Javascript object>

### The results of one function can be used as the input to another function

$$ g(z) = \frac{z}{e^{z}}$$

In [82]:
def find_g(my_z):

    result = my_z / np.exp(my_z)
    return result

<IPython.core.display.Javascript object>

In [83]:
find_g(value_f)

array([ 0.1947002 ,  0.16400133,  0.06634875, -0.09392464, -0.25816119,
       -0.32021325, -0.23061811, -0.05927586,  0.0910947 ,  0.17502291,
        0.19354366,  0.15038426,  0.03900318, -0.12893185, -0.28157559,
       -0.31391242, -0.19983141, -0.02566909,  0.11312798,  0.1835327 ])

<IPython.core.display.Javascript object>

In [84]:
find_g(find_f(scalar_a, scalar_b, array_x))

array([ 0.1947002 ,  0.16400133,  0.06634875, -0.09392464, -0.25816119,
       -0.32021325, -0.23061811, -0.05927586,  0.0910947 ,  0.17502291,
        0.19354366,  0.15038426,  0.03900318, -0.12893185, -0.28157559,
       -0.31391242, -0.19983141, -0.02566909,  0.11312798,  0.1835327 ])

<IPython.core.display.Javascript object>

# Creating Arrays

## Numpy has a wide variety of ways of creating arrays: [Array creation routines](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html)

In [85]:
# a new array filled with zeros

array_0 = np.zeros(10)

array_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<IPython.core.display.Javascript object>

In [86]:
# a new array filled with ones

array_1 = np.ones(10)

array_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<IPython.core.display.Javascript object>

In [87]:
# a new array filled with evenly spaced values within a given interval

array_2 = np.arange(10,20)

array_2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

<IPython.core.display.Javascript object>

In [88]:
# a new array filled with evenly spaced numbers over a specified interval (start, stop, num)

array_3 = np.linspace(10,20,5)

array_3

array([10. , 12.5, 15. , 17.5, 20. ])

<IPython.core.display.Javascript object>

In [89]:
# a new array filled with evenly spaced numbers over a log scale. (start, stop, num, base)

array_4 = np.logspace(1,2,5,10)

array_4

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

<IPython.core.display.Javascript object>